# when using the default proxy server port
#local_backend: true

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/uploads
public_folder: /uploads
collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Header Image", name: "headerImage", widget: "image"}
          - {label: "About Text", name: "aboutText", widget: "text"}
          - {label: "Advantages", name: "advantages", widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Background Image", name: "bgImage", widget: "image" },
              {label: "Text", name: "text", widget: "text"},
              {label: "Second Heading", name: "subHeading", widget: string },
              {label: "Right Image", name: "rightImage", widget: "image" },
              {label: "Advantages", name: "advantages", widget: list, fields: [
                {label: "Title", name: "title", widget: string }
              ]}
            ]}
          - {label: "Video Section", name: "videoSection", widget: object, fields: [
              {label: "Section Title", name: "title", widget: string },
              {label: "Youtube Video ID", name: "youtubeUrl", widget: string }
            ]}
          - {label: "Catalogue Section", name: "catalogueSection", widget: object, fields: [
              {label: "Section Title", name: "title", widget: string },
              {label: "Catalogue Image 1", name: "imageUrl_1", widget: "image" },
              {label: "Catalogue Image 2", name: "imageUrl_2", widget: "image" },
              {label: "Catalogue Image 3", name: "imageUrl_3", widget: "image" },
              {label: "Catalogue Image 4", name: "imageUrl_4", widget: "image" },
              {label: "Catalogue Image 5", name: "imageUrl_5", widget: "image" }
            ]}
          - {label: "Form Section", name: "formSection", widget: object, fields: [
              {label: "Section Title", name: "title", widget: string },
              {label: "Form Button Text", name: "btnText", widget: string }
            ]}
          - {label: "Saunas", name: "saunas", widget: object, fields: [
              {label: "Section Title", name: "title", widget: string },
              {label: "Sauna Groups", name: "saunaGroups", widget: list, fields: [
                {label: "Group Title", name: "title", widget: string },
                {label: "Group Wrap", name: "itemsWrap", widget: "boolean", default: true },
                {label: "Group Button Text", name: "btnText", widget: string },
                {label: "Sauna", name: "sauna", widget: "list", fields: [
                  {label: "Sauna Name", name: "saunaName", widget: string },
                  {label: "Sauna Image", name: "saunaImage", widget: "image" },
                  {label: "Sauna PDF", name: "sauna_pdf", widget: "file" }
                ]}
              ]}
            ]}
          - {label: "CTA: Our Specialists", name: "ctaSpecialists", widget: object, fields: [
              {label: "Small Title", name: "smallTitle", widget: string },
              {label: "Big Title", name: "bigTitle", widget: string },
              {label: "Button Text", name: "btnText", widget: string },
              {label: "Button Phone", name: "btnPhone", widget: string },
              {label: "Specialist Image", name: "imageUrl", widget: "image" }
            ]}
          - {label: "Features", name: "features", widget: list, fields: [
              {label: "Title", name: "title", widget: string },
              {label: "Icon", name: "icon", widget: "image" }
            ]}
          - {label: "Warranty Section", name: "warrantySection", widget: object, fields: [
              {label: "Section Title", name: "title", widget: string },
              {label: "Section Text", name: "text", widget: "text" },
              {label: "Warranty Icons", name: "icons", widget: list, fields: [
                {label: "Icon", name: "iconUrl", widget: "image" }
              ]}
            ]}
          - {label: "Footer Section", name: "footerSection", widget: object, fields: [
              {label: "Footer Links", name: "footerLinks", widget: list, fields: [
                {label: "Link Title", name: "linkTitle", widget: string }
              ]},
              {label: "Copyright Text", name: "copy", widget: string }
            ]}
